### ISSUE TITLE
Manage version of org.apache.sling.commons.threads

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.maven.aem-dependencies#7]
For certain test cases it is important to inject a ThreadPoolManager service implementation (org.apache.sling.commons.threads.impl.DefaultThreadPoolManager). In order to use this an explicit dependency to `org.apache.sling:org.apache.sling.commons.threads` is necessary. It would be handy to have that dependency managed as well (for usage with `test` scope)

**Comment by kwin** [comment]
Thanks a lot for the quick fix.

**Comment by stefanseifert** [comment]
please give a notice in case you need a release soon

**Comment by kwin** [comment]
No need for a quick release, I can wait for the next regular SP release.
